version: "3.9"

services:
  app01:
    build:
        context: .
        dockerfile: ./app/Dockerfile
    container_name: e8-app1
    networks:
      - net-e08
    ports:
      - 8080:8080


  app02:
    build:
        context: .
        dockerfile: ./app/Dockerfile
    container_name: e8-app2
    networks:
      - net-e08
    ports:
      - 8081:8080


  nginx-lb:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: e8-lb-nginx
    ports:
      - 9090:80
    networks:
      - net-e08
    depends_on:
       - app01
       - app02
    links: 
       - app01
       - app02

networks:
  net-e08:
    external: true